version: 2
updates:
  ##### GitHub Actions #####
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-github-actions-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "sebbi08"
    labels:
      - "dependencies"

  ##### npm #####
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "sebbi08"
    labels:
      - "dependencies"

  ##### Docker #####
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-docker-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "sebbi08"
    labels:
      - "dependencies"

  ##### Docker #####
  - package-ecosystem: "docker"
    directory: "/.dev"
    schedule:
      interval: "weekly"
    groups:
      update-docker-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "sebbi08"
    labels:
      - "dependencies"
