version: 2
updates:
  ##### GitHub Actions #####
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-github-actions-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
    labels:
      - "dependencies"

  ##### npm #####
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/sdk"
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@nmshd/runtime"
          - "@nmshd/content"
          - "@nmshd/core-types"
      update-runtime:
        patterns:
          - "@nmshd/runtime"
          - "@nmshd/content"
          - "@nmshd/core-types"
    reviewers:
      - "jkoenig134"
      - "Milena-Czierlinski"
    labels:
      - "dependencies"

  ##### Docker #####
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/.dev"
    schedule:
      interval: "weekly"
    groups:
      update-docker-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "Milena-Czierlinski"
    labels:
      - "dependencies"
