version: 2
updates:
  ##### GitHub Actions #####
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-github-actions-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "sebbi08"
    labels:
      - "dependencies"

  ##### npm #####
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/sdk"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@nmshd/content"
      - dependency-name: "@nmshd/runtime"
      - dependency-name: "@nmshd/core-types"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "sebbi08"
    labels:
      - "dependencies"

  ##### Docker #####
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/.dev"
    schedule:
      interval: "weekly"
    groups:
      update-docker-dependencies:
        patterns:
          - "*"
    reviewers:
      - "jkoenig134"
      - "sebbi08"
    labels:
      - "dependencies"
