services:
  connector-1:
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    container_name: connector-1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:80" # Webserver
      - "9229:9229" # Debugger
    environment:
      - CUSTOM_CONFIG_LOCATION=/config.json
      - SYNC_ENABLED=${SYNC_ENABLED:-false}
      - DATABASE_NAME=${DATABASE_NAME_PREFIX:-connector}-1
      - transportLibrary__baseUrl
      - transportLibrary__addressGenerationHostnameOverride
      - transportLibrary__platformClientId
      - transportLibrary__platformClientSecret
      - modules__sse__enabled=${modules__sse__enabled:-false}
      - modules__sse__baseUrlOverride
    volumes:
      - ..:/usr/app
      - ./config.json:/config.json:ro
    depends_on:
      - mongo
      - mongo-express
    stdin_open: true
    tty: true

  connector-2:
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    container_name: connector-2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:80" # Webserver
      - "9231:9229" # Debugger
    environment:
      - CUSTOM_CONFIG_LOCATION=/config.json
      - SYNC_ENABLED=${SYNC_ENABLED:-false}
      - DATABASE_NAME=${DATABASE_NAME_PREFIX:-connector}-2
      - transportLibrary__baseUrl
      - transportLibrary__addressGenerationHostnameOverride
      - transportLibrary__platformClientId
      - transportLibrary__platformClientSecret
      - modules__sse__enabled=${modules__sse__enabled:-false}
      - modules__sse__baseUrlOverride
    volumes:
      - ..:/usr/app
      - ./config.json:/config.json:ro
    depends_on:
      - mongo
      - mongo-express
    stdin_open: true
    tty: true

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo@sha256:a6bda40d00e56682aeaa1bfc88e024b7dd755782c575c02760104fe02010f94f
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    logging:
      driver: none

  mongo-express:
    container_name: mongo-express
    image: mongo-express@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64
    ports:
      - "3003:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: lucario
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo_data:
