services:
  consumer-api:
    image: ghcr.io/nmshd/backbone-consumer-api:6.56.5@sha256:619b6eb215550567bf003d9cf3385ab51a1b200f4709fdbd9d3b5e49d5d8aae8
    container_name: consumer-api
    hostname: consumer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      azure-storage-emulator:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
      sse-server:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  event-handler-service:
    image: ghcr.io/nmshd/backbone-event-handler:6.56.5@sha256:a592b63963d41dbb456e95ffc1f582c78454ec547b30de897b5be8fb4cecca9b
    container_name: event-handler-service
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  sse-server:
    image: ghcr.io/nmshd/backbone-sse-server:6.56.5@sha256:c2a43bc73c34f8b8d29d8e043bd3cdc84aefe9d1454ee7b21d2e3dace3570915
    container_name: sse-server
    hostname: sse-server
    ports:
      - "8092:8080"
    depends_on:
      database:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  database-migrator:
    container_name: database-migrator-test
    image: ghcr.io/nmshd/backbone-database-migrator:6.56.5@sha256:841bfce91c62a5a83ffe6fe700abdbfc4bb6905293b8bf6dcfb3261fb880f6db
    environment:
      Infrastructure__SqlDatabase__Provider: Postgres
      Infrastructure__SqlDatabase__ConnectionString: "Server=postgres;Database=enmeshed;User Id=postgres;Password=Passw0rd;Port=5432"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      database:
        condition: service_healthy
    configs:
      - source: Config
        target: app/appsettings.override.json

  ### infrastructure ###

  database:
    container_name: bkb-postgres
    hostname: postgres
    image: postgres@sha256:feff5b24fedd610975a1f5e743c51a4b360437f4dc3a11acf740dcd708f413f6
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  azure-storage-emulator:
    container_name: azure-storage-emulator
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0"
    pull_policy: always

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.1.4-alpine@sha256:0d74affad41fc3f63d945578e344b683f054289b52949f971fce8797f88fc036

  ### seeds ###

  seed-client:
    container_name: seed-client
    image: ghcr.io/nmshd/backbone-admin-cli:6.56.5@sha256:6d493ee48ef8d3c12b6979fd151fcc0ba7f85b679f3fc881860e4c67c3f5f0a2
    depends_on:
      consumer-api:
        condition: service_healthy
    command: backbone client create --clientId test --clientSecret test --defaultTier Basic
    configs:
      - source: Config
        target: app/appsettings.override.json

configs:
  Config:
    file: appsettings.override.json
