name: local-test-backbone

services:
  consumer-api:
    image: ghcr.io/nmshd/backbone-consumer-api:7.1.10@sha256:da19cd9902b51244697486fc4decb02323053cdb89c784932981f75efd2e1cf1
    container_name: consumer-api
    hostname: consumer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      azure-storage-emulator:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
      sse-server:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  event-handler-service:
    image: ghcr.io/nmshd/backbone-event-handler:7.1.10@sha256:dcba3c05b2bfa03f0f5880ec9e71fbbb0bab0ee372656e33e93b1590cacfb2aa
    container_name: event-handler-service
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  sse-server:
    image: ghcr.io/nmshd/backbone-sse-server:7.1.10@sha256:fe48b59263e3590bd51ba660591bc28f2a75e67a04922f52d1ce6c7605ecabeb
    container_name: sse-server
    hostname: sse-server
    ports:
      - "8092:8080"
    depends_on:
      database:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  admin-ui:
    image: ghcr.io/nmshd/backbone-admin-ui:7.1.10@sha256:e76732c1aa4ea0e2eb19f4433bfe5a52222a1697ce93bf52f27501c52738341f
    container_name: admin-ui
    hostname: admin-ui
    ports:
      - "8091:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      consumer-api:
        condition: service_healthy
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  database-migrator:
    container_name: database-migrator
    image: ghcr.io/nmshd/backbone-database-migrator:7.1.10@sha256:164831ac5523bfb65e4880c12bc5e8819619f3eb43e13e1b76bbbe3b2e6bbb61
    environment:
      Infrastructure__SqlDatabase__Provider: Postgres
      Infrastructure__SqlDatabase__ConnectionString: "Server=postgres;Database=enmeshed;User Id=postgres;Password=Passw0rd;Port=5432"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      database:
        condition: service_healthy
    configs:
      - source: Config
        target: app/appsettings.override.json

  ### infrastructure ###

  database:
    container_name: bkb-postgres
    hostname: postgres
    image: postgres@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  azure-storage-emulator:
    container_name: azure-storage-emulator
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite@sha256:76b8127d608fab8287a14a4bfeb9a5502cdcffb4bf1e86f09f324ebb0e70edba
    pull_policy: always
    command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0" --skipApiVersionCheck

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.3.4-alpine@sha256:c07a5e60f5429be18b3b7fd3a4dfa9a84c3372f88df084b6f2b22224192c360c

  ### seeds ###

  seed-client:
    container_name: seed-client
    image: ghcr.io/nmshd/backbone-admin-cli:7.1.10@sha256:3fe8917190e53f71328cb212947a827e3d74e81fffa6ea4d1ad0a962484deb83
    depends_on:
      consumer-api:
        condition: service_healthy
    command: backbone client create --clientId test --clientSecret test --defaultTier Basic
    configs:
      - source: Config
        target: app/appsettings.override.json

networks:
  default:
    name: local-test-backbone

configs:
  Config:
    file: appsettings.override.json
