name: local-test-backbone

services:
  consumer-api:
    image: ghcr.io/nmshd/backbone-consumer-api:7.0.3@sha256:d7f43607dc7763430498b418c47a3c0f291ec78f26876c3fbe9aa04d318631ba
    container_name: consumer-api
    hostname: consumer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      azure-storage-emulator:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
      sse-server:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  event-handler-service:
    image: ghcr.io/nmshd/backbone-event-handler:7.0.3@sha256:fb18cef8dde19ac36212eb617321d906e181973c7d4d28cd6b3bee71215d98f4
    container_name: event-handler-service
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  sse-server:
    image: ghcr.io/nmshd/backbone-sse-server:7.0.3@sha256:173ec068804f0fbb042020f4011c6be553fd4ecdbf8f8ce8d6ab9679b8fe548e
    container_name: sse-server
    hostname: sse-server
    ports:
      - "8092:8080"
    depends_on:
      database:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  admin-ui:
    image: ghcr.io/nmshd/backbone-admin-ui:7.0.3@sha256:b0cb4ee0b426bae7d8d1890294b72e69e6adf8e791baf5d962aa2f19e5a553d9
    container_name: admin-ui
    hostname: admin-ui
    ports:
      - "8091:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      consumer-api:
        condition: service_healthy
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  database-migrator:
    container_name: database-migrator
    image: ghcr.io/nmshd/backbone-database-migrator:7.0.3@sha256:61f2fba1a0774997c730f9f7015eaf317369701a1b2f934ef8c76a8de89b18d5
    environment:
      Infrastructure__SqlDatabase__Provider: Postgres
      Infrastructure__SqlDatabase__ConnectionString: "Server=postgres;Database=enmeshed;User Id=postgres;Password=Passw0rd;Port=5432"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      database:
        condition: service_healthy
    configs:
      - source: Config
        target: app/appsettings.override.json

  ### infrastructure ###

  database:
    container_name: bkb-postgres
    hostname: postgres
    image: postgres@sha256:38d5c9d522037d8bf0864c9068e4df2f8a60127c6489ab06f98fdeda535560f9
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  azure-storage-emulator:
    container_name: azure-storage-emulator
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    pull_policy: always
    command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0"

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.2.1-alpine@sha256:2ed5394838c8062947c0b0f298f9fe0f623c8337c6e400dce91ef93c5c1f6c11

  ### seeds ###

  seed-client:
    container_name: seed-client
    image: ghcr.io/nmshd/backbone-admin-cli:7.0.3@sha256:47cc66ceabb59009356d4508af66fcb718c9f9cd69759b5bfacaabe198b3ff78
    depends_on:
      consumer-api:
        condition: service_healthy
    command: backbone client create --clientId test --clientSecret test --defaultTier Basic
    configs:
      - source: Config
        target: app/appsettings.override.json

networks:
  default:
    name: local-test-backbone

configs:
  Config:
    file: appsettings.override.json
