include:
  - compose.backbone.yml

services:
  connector:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        VERSION: "1.0.0"
        BUILD_NUMBER: "test"
        COMMIT_HASH: "test"
    container_name: connector
    ports:
      - "3000:80" # Webserver
    environment:
      DATABASE_NAME: "prod_connector"
      transportLibrary__baseUrl: "http://consumer-api:8080"
      transportLibrary__platformClientId: "test"
      transportLibrary__platformClientSecret: "test"
      transportLibrary__addressGenerationHostnameOverride: "localhost"
      DATABASE_CONNECTION_STRING: "mongodb://mongo:27017"
      API_KEY: This_is_a_test_APIKEY_with_30_chars+
      DEBUG: true
    depends_on:
      mongo:
        condition: service_started
      consumer-api:
        condition: service_healthy

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo@sha256:f331890607b5cdce091da9823f91ab1e4c54d31fd572282037880b2eaafff454
    ports:
      - "27017:27017"
    logging:
      driver: none
