name: local-test-backbone

services:
  consumer-api:
    image: ghcr.io/nmshd/backbone-consumer-api:7.1.6@sha256:594a3741ef85e226c9425f2f05bc14742586513f9d4be536390b66e87440b31b
    container_name: consumer-api
    hostname: consumer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      azure-storage-emulator:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
      sse-server:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  event-handler-service:
    image: ghcr.io/nmshd/backbone-event-handler:7.1.6@sha256:36ab4018030a96e14cc93014114c941aeb19dd6f73b1bad080e433cbfb2acde4
    container_name: event-handler-service
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  sse-server:
    image: ghcr.io/nmshd/backbone-sse-server:7.1.6@sha256:1c6feadf37d60a28752e37566e2101c8d84926c9cbb201cb3685b53963107c40
    container_name: sse-server
    hostname: sse-server
    ports:
      - "8092:8080"
    depends_on:
      database:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  admin-ui:
    image: ghcr.io/nmshd/backbone-admin-ui:7.1.6@sha256:4cacbda5cf15ff53388ac51f02fc82e3a4a0df235d0f350dc1239b140d831b22
    container_name: admin-ui
    hostname: admin-ui
    ports:
      - "8091:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      consumer-api:
        condition: service_healthy
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  database-migrator:
    container_name: database-migrator
    image: ghcr.io/nmshd/backbone-database-migrator:7.1.6@sha256:f44463234a4dd171ed974990c9e1e8b7710959806107c5ac9c2a9a193b116331
    environment:
      Infrastructure__SqlDatabase__Provider: Postgres
      Infrastructure__SqlDatabase__ConnectionString: "Server=postgres;Database=enmeshed;User Id=postgres;Password=Passw0rd;Port=5432"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      database:
        condition: service_healthy
    configs:
      - source: Config
        target: app/appsettings.override.json

  ### infrastructure ###

  database:
    container_name: bkb-postgres
    hostname: postgres
    image: postgres@sha256:f7ce845ee6873dd84be93c9828fe0d1fab0f9707dc9ac569694657398b290bce
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  azure-storage-emulator:
    container_name: azure-storage-emulator
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    pull_policy: always
    command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0" --skipApiVersionCheck

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.3.0-alpine@sha256:4f4a74fe951bb8bebae41187c8592ac0737e63d929467502f17689b22e9e9204

  ### seeds ###

  seed-client:
    container_name: seed-client
    image: ghcr.io/nmshd/backbone-admin-cli:7.1.6@sha256:0aae9aded1c046bfcd93fcb2675d52d2e301485a3bf7534895b6701c14978613
    depends_on:
      consumer-api:
        condition: service_healthy
    command: backbone client create --clientId test --clientSecret test --defaultTier Basic
    configs:
      - source: Config
        target: app/appsettings.override.json

networks:
  default:
    name: local-test-backbone

configs:
  Config:
    file: appsettings.override.json
