name: local-test-backbone

services:
  consumer-api:
    image: ghcr.io/nmshd/backbone-consumer-api:7.1.4@sha256:3b2246b551f576982e99c4fe23cbb7fa8eae4c59956233761d877318d9ba86f2
    container_name: consumer-api
    hostname: consumer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      azure-storage-emulator:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
      sse-server:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  event-handler-service:
    image: ghcr.io/nmshd/backbone-event-handler:7.1.4@sha256:f4b2795e317e867b507a193f53adeb9aab48fc32e3ba4a58fdcb2ec0781741da
    container_name: event-handler-service
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  sse-server:
    image: ghcr.io/nmshd/backbone-sse-server:7.1.4@sha256:96acdb1ea8f9f5a3cf89ea89189086ecadebe8cf069af404a0d4563b551b853d
    container_name: sse-server
    hostname: sse-server
    ports:
      - "8092:8080"
    depends_on:
      database:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  admin-ui:
    image: ghcr.io/nmshd/backbone-admin-ui:7.1.4@sha256:66c65b7eb9f388e5629bd019c7ab4bc170d81bf84a650823b330034ec0155f9e
    container_name: admin-ui
    hostname: admin-ui
    ports:
      - "8091:8080"
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_started
      consumer-api:
        condition: service_healthy
      database-migrator:
        condition: service_completed_successfully
    configs:
      - source: Config
        target: app/appsettings.override.json

  database-migrator:
    container_name: database-migrator
    image: ghcr.io/nmshd/backbone-database-migrator:7.1.4@sha256:80953d2ba69353c8aeacc70051249b43c972b358fad2a94158af2e49ccee6dce
    environment:
      Infrastructure__SqlDatabase__Provider: Postgres
      Infrastructure__SqlDatabase__ConnectionString: "Server=postgres;Database=enmeshed;User Id=postgres;Password=Passw0rd;Port=5432"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      database:
        condition: service_healthy
    configs:
      - source: Config
        target: app/appsettings.override.json

  ### infrastructure ###

  database:
    container_name: bkb-postgres
    hostname: postgres
    image: postgres@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  azure-storage-emulator:
    container_name: azure-storage-emulator
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    pull_policy: always
    command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0" --skipApiVersionCheck

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.3.0-alpine@sha256:4f4a74fe951bb8bebae41187c8592ac0737e63d929467502f17689b22e9e9204

  ### seeds ###

  seed-client:
    container_name: seed-client
    image: ghcr.io/nmshd/backbone-admin-cli:7.1.4@sha256:b07d9b30d7b54572ea37cf0d6d91bbb7c067011a45c55cdd60683f9604348a04
    depends_on:
      consumer-api:
        condition: service_healthy
    command: backbone client create --clientId test --clientSecret test --defaultTier Basic
    configs:
      - source: Config
        target: app/appsettings.override.json

networks:
  default:
    name: local-test-backbone

configs:
  Config:
    file: appsettings.override.json
