FROM dhi.io/node:25.2.0-dev AS builder
WORKDIR /usr/app

# Webserver, Debugger
EXPOSE 80 9229

ENTRYPOINT ["npx", "nodemon", "-e", "js,json,yml", "--watch", "./dist", "--watch", "./config", "--inspect=0.0.0.0:9229", "--nolazy", "./dist/index.js", "start"]
