apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enmeshed_connector.name" . }}
  {{- with .Values.pod.annotations }}
  annotations:
    {{- toYaml . | nindent  }}
  {{- end }}
  labels:
    {{- include "enmeshed_connector.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "enmeshed_connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      labels:
        {{- include "enmeshed_connector.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.pod.securityContext | nindent 8 }}
      containers:
        - name: connector
          securityContext: {{- toYaml .Values.pod.containerSecurityContext | nindent 12 }}
          image: "ghcr.io/nmshd/connector:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pod.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.pod.resources | nindent 12 }}
          env: {{ append .Values.pod.environment (dict "name" "CUSTOM_CONFIG_LOCATION" "value" "/config.json") | toYaml | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /config.json
              subPath: config.json
              readOnly: true
        {{ if .Values.pod.ferretdb.enabled }}
        - name: ferretdb
          image: "ghcr.io/ferretdb/ferretdb:{{ .Values.pod.ferretdb.tag }}"
          imagePullPolicy: IfNotPresent
          env: {{ .Values.pod.ferretdb.environment | toYaml | nindent 12 }}
        {{ end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "enmeshed_connector.name" . }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
