apiVersion: v1
kind: Pod
metadata:
  name: {{ include "enmeshed_connector.name" . }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "enmeshed_connector.labels" . | nindent 4 }}
spec:
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 8 }}
  containers:
    - name: connector
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /health
          port: http
      readinessProbe:
        httpGet:
          path: /health
          port: http
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
      env: {{ append .Values.environment (dict "name" "CUSTOM_CONFIG_LOCATION" "value" "/config.json") | toYaml | nindent 8 }}
      volumeMounts:
        - name: config-volume
          mountPath: /config.json
          subPath: config.json
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: {{ include "enmeshed_connector.name" . }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
