name: Coverage

on:
  push:
    branches: [main]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash .ci/runChecks.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Backbone
        run: npm run start:backbone
      - uses: actions/setup-node@v4
        with:
          node-version: current
      - run: npm ci
      - run: npm run build:ci --workspaces --if-present
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@v1
      - run: npm run test:ci --workspaces --if-present
        env:
          DATABASE_CONNECTION_STRING: mongodb://127.0.0.1:27017
          NMSHD_TEST_BASEURL: http://localhost:8090
          NMSHD_TEST_CLIENTID: test
          NMSHD_TEST_CLIENTSECRET: test

      - name: Code coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage/cobertura-coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
