name: Publish

on:
  push:
    branches: [main, release/**]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash .ci/runChecks.sh

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build:ci --workspaces --if-present
      - run: bash .ci/publishNpm.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: ["run-checks"]

  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: bash .ci/buildAndPush.sh
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          COMMIT_HASH: ${{ github.sha }}
    needs: ["run-checks"]

  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "$PASSWORD" | helm registry login -u $USER --password-stdin https://ghcr.io
        env:
          USER: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - run: bash .ci/publishHelmChart.sh
    needs: ["publish-docker"]
