name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "$PASSWORD" | helm registry login -u $USER --password-stdin https://ghcr.io
        env:
          USER: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - run: bash .ci/publishHelmChart.sh
