name: Publish

on:
  push:
    tags: "*"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: current
      - run: bash .ci/runChecks.sh

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: current
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build:ci --workspaces --if-present
      - run: bash .ci/publishNpm.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ github.ref_name }}
    needs: ["run-checks"]

  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: bash .ci/buildAndPush.sh
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          COMMIT_HASH: ${{ github.sha }}
          VERSION: ${{ github.ref_name }}
    needs: ["run-checks"]

  publish-zipped-connector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: current
          registry-url: https://registry.npmjs.org/
      - uses: gr2m/await-npm-package-version-action@v1
        with:
          package: "@nmshd/connector-types"
          version: ${{ github.ref_name }}
          registry: https://registry.npmjs.org
      - name: Put the connector types package into the cache
        run: npm cache add @nmshd/connector-types && npm cache verify
      - run: bash .ci/buildConnectorZip.sh
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          COMMIT_HASH: ${{ github.sha }}
          VERSION: ${{ github.ref_name }}
      - name: Add zipped connector to release
        uses: softprops/action-gh-release@v2
        with:
          files: connector-${{ github.ref_name }}.zip
    needs: ["publish-npm"]

  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - run: echo "$PASSWORD" | helm registry login -u $USER --password-stdin https://ghcr.io
        env:
          USER: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - run: bash .ci/publishHelmChart.sh
        env:
          VERSION: ${{ github.ref_name }}
    needs: ["publish-docker"]
